model_path: ~/.cache/models/vision/mobilesam1/mobilesam_encoder_tiny_sim.fp16.onnx
class: deploy.mobilesam1.MobileSAMSegmentor
test_image: ~/.cache/assets/image/008_picture.jpg
default_params:
  decoder_model_path: ~/.cache/models/vision/mobilesam1/mobilesam_decoder_sim.dynq.onnx
  num_threads: 4
  providers:
    - SpaceMITExecutionProvider
