model_path: ~/.cache/models/vision/mixformer/mixformer_v2.q.onnx
test_video: ~/.cache/assets/video/004_bag.avi
class: deploy.mixformer.MixFormerTracker
initial_bbox:
  x: 315
  y: 140
  w: 116
  h: 121
default_params:
  num_threads: 4
  update_interval: 200
  update_threshold: 0.5
  max_score_decay: 1.0
  providers:
    - SpaceMITExecutionProvider
